
//This file should be called cbmc_main_MQL.c
//This is autogenerated code. Edit by hand at your peril!

//It can be used with the cbmc model checker
//Call it using the following command: 
//$ cbmc cbmc_main_MQL.c F_MQL.c


#include "F_MQL.h"
#include <stdio.h>
#include <stdint.h>

int main() {


	//I/O and state for MQL
	enforcervars_MQL_t enf_MQL;
    inputs_MQL_t inputs_MQL;
    outputs_MQL_t outputs_MQL;

	//set values to known state
    MQL_init_all_vars(&enf_MQL, &inputs_MQL, &outputs_MQL);

	//introduce nondeterminism
    //a nondet_xxxxx function name tells cbmc that it could be anything, but must be unique
    //randomise inputs
	

	//randomise enforcer state, i.e. clock values and position (excepting violation state)
	enf_MQL.c_age = nondet_MQL_enf_MQL_Policy_0();
	
	
	enf_MQL._policy_MQL_Policy_state = nondet_MQL_enf_MQL_Policy_state() % 2;
	

    //run the enforcer (i.e. tell CBMC to check this out)
	MQL_run_via_enforcer(&enf_MQL, &inputs_MQL, &outputs_MQL);

}


void MQL_run(inputs_MQL_t *inputs, outputs_MQL_t *outputs) {
    //randomise controller

    outputs->act_PLACE = nondet_MQL_output_0();
	outputs->act_CANCEL = nondet_MQL_output_1();
	 
}

