
//This file should be called F_MQL.c
//This is autogenerated code. Edit by hand at your peril!
#include "F_MQL.h"

void MQL_init_all_vars(enforcervars_MQL_t* me, inputs_MQL_t* inputs, outputs_MQL_t* outputs) {
	//set any input vars with default values
	
	//set any output vars with default values
	

	
	me->_policy_MQL_Policy_state = POLICY_STATE_MQL_MQL_Policy_empty;
	//input policy internal vars
	
	me->c_age = 0;
	
	
}

void MQL_run_via_enforcer(enforcervars_MQL_t* me, inputs_MQL_t* inputs, outputs_MQL_t* outputs) {
	//run the policies in reverse order for the inputs (last policies have highest priority)
	
	 MQL_run_input_enforcer_MQL_Policy(me, inputs);
	

	MQL_run(inputs, outputs);

	//run policies in specified order for outputs
	MQL_run_output_enforcer_MQL_Policy(me, inputs,outputs);
	
}


//input policies

//INPUT POLICY MQL_Policy BEGIN
//This will run the input enforcer for MQL's policy MQL_Policy
void MQL_run_input_enforcer_MQL_Policy(enforcervars_MQL_t* me, inputs_MQL_t* inputs) {
	switch(me->_policy_MQL_Policy_state) {
		case POLICY_STATE_MQL_MQL_Policy_empty:
			
			
			break;

		case POLICY_STATE_MQL_MQL_Policy_resting:
			
			if(me->c_age < CONST_MQL_Policy_T_MQL) {
				//transition resting -> violation on c_age < T_MQL
				//select a transition to solve the problem
				
				//Recovery instructions manually provided.
				
			} 
			
			break;

		
	}
}

//INPUT POLICY MQL_Policy END



//output policies

//OUTPUT POLICY MQL_Policy BEGIN
//This will run the input enforcer for MQL's policy MQL_Policy
void MQL_run_output_enforcer_MQL_Policy(enforcervars_MQL_t* me, inputs_MQL_t* inputs, outputs_MQL_t* outputs) {
	//advance timers
	
	me->c_age++;
	
	//run enforcer
	switch(me->_policy_MQL_Policy_state) {
		case POLICY_STATE_MQL_MQL_Policy_empty:
			

			break;

		case POLICY_STATE_MQL_MQL_Policy_resting:
			
			if(outputs->act_CANCEL && me->c_age < CONST_MQL_Policy_T_MQL) {
				//transition resting -> violation on act_CANCEL and c_age < T_MQL
				//select a transition to solve the problem
				
				//Recovery instructions manually provided.
				outputs->act_CANCEL = 0;
				
			} 

			break;

		
	}

	//select transition to advance state
	switch(me->_policy_MQL_Policy_state) {
		case POLICY_STATE_MQL_MQL_Policy_empty:
			
			if(outputs->act_PLACE) {
				//transition empty -> resting on act_PLACE
				me->_policy_MQL_Policy_state = POLICY_STATE_MQL_MQL_Policy_resting;
				//set expressions
				
				me->c_age = 0;
				break;
			} 
			if( !(outputs->act_PLACE)) {
				//transition empty -> empty on !act_PLACE
				me->_policy_MQL_Policy_state = POLICY_STATE_MQL_MQL_Policy_empty;
				//set expressions
				
				break;
			} 
			
			//ensure a transition was taken in this state
			assert(false && "MQL_MQL_Policy_empty must take a transition"); //if we are still here, then no transition was taken and we are no longer satisfying liveness

			break;

		case POLICY_STATE_MQL_MQL_Policy_resting:
			
			if(outputs->act_CANCEL && me->c_age >= CONST_MQL_Policy_T_MQL) {
				//transition resting -> empty on act_CANCEL and c_age >= T_MQL
				me->_policy_MQL_Policy_state = POLICY_STATE_MQL_MQL_Policy_empty;
				//set expressions
				
				break;
			} 
			if( !(outputs->act_CANCEL)) {
				//transition resting -> resting on !act_CANCEL
				me->_policy_MQL_Policy_state = POLICY_STATE_MQL_MQL_Policy_resting;
				//set expressions
				
				break;
			} 
			if(outputs->act_CANCEL && me->c_age < CONST_MQL_Policy_T_MQL) {
				//transition resting -> violation on act_CANCEL and c_age < T_MQL
				me->_policy_MQL_Policy_state = POLICY_STATE_MQL_MQL_Policy_violation;
				//set expressions
				
				break;
			} 
			
			//ensure a transition was taken in this state
			assert(false && "MQL_MQL_Policy_resting must take a transition"); //if we are still here, then no transition was taken and we are no longer satisfying liveness

			break;

		
	}

	//ensure we did not violate (i.e. we did not enter violation state)
	assert(me->_policy_MQL_Policy_state != POLICY_STATE_MQL_MQL_Policy_violation);
}

//OUTPUT POLICY MQL_Policy END



//This function is provided in "F_MQL.c"
//It will check the state of the enforcer monitor code
//It returns one of the following:
//0: currently true (safe)
//1: always true (safe)
//-1: currently false (unsafe)
//-2: always false (unsafe)
//It will need to do some reachability analysis to achieve this

