
//This file should be called F_MQL.h
//This is autogenerated code. Edit by hand at your peril!

#include <stdint.h>
#include <stdbool.h>
#include <assert.h>

//the dtimer_t type
typedef uint64_t dtimer_t;

//For each policy, we need an enum type for the state machine

enum MQL_policy_MQL_Policy_states { 
	POLICY_STATE_MQL_MQL_Policy_empty, 
	POLICY_STATE_MQL_MQL_Policy_resting,
	POLICY_STATE_MQL_MQL_Policy_violation 
};


//Inputs to the function MQL
typedef struct {
	
} inputs_MQL_t;

//Outputs from the function MQL
typedef struct {
	bool act_PLACE;
	bool act_CANCEL;
	
} outputs_MQL_t;

//enforcer state and vars:
typedef struct {
	enum MQL_policy_MQL_Policy_states _policy_MQL_Policy_state;
	//internal vars
	dtimer_t c_age;
	
	
	
} enforcervars_MQL_t;


#define CONST_MQL_Policy_T_MQL 100


//This function is provided in "F_MQL.c"
//It sets up the variable structures to their initial values
void MQL_init_all_vars(enforcervars_MQL_t* me, inputs_MQL_t* inputs, outputs_MQL_t* outputs);

//This function is provided in "F_MQL.c"
//It will run the synthesised enforcer and call the controller function
void MQL_run_via_enforcer(enforcervars_MQL_t* me, inputs_MQL_t* inputs, outputs_MQL_t* outputs);

//This function is provided from the user
//It is the controller function
extern void MQL_run(inputs_MQL_t* inputs, outputs_MQL_t* outputs);

//enforcer functions


//This function is provided in "F_MQL.c"
//It will run the input enforcer for MQL's policy MQL_Policy
void MQL_run_input_enforcer_MQL_Policy(enforcervars_MQL_t* me, inputs_MQL_t* inputs);

//This function is provided in "F_MQL.c"
//It will run the input enforcer for MQL's policy MQL_Policy
void MQL_run_output_enforcer_MQL_Policy(enforcervars_MQL_t* me, inputs_MQL_t* inputs, outputs_MQL_t* outputs);

//This function is provided in "F_MQL.c"
//It will check the state of the enforcer monitor code
//It returns one of the following:
//0: currently true (safe)
//1: always true (safe)
//-1: currently false (unsafe)
//-2: always false (unsafe)
//It will need to do some reachability analysis to achieve this
int MQL_check_rv_status_MQL_Policy(enforcervars_MQL_t* me);


