
//This file should be called F_OTR.c
//This is autogenerated code. Edit by hand at your peril!
#include "F_OTR.h"

void OTR_init_all_vars(enforcervars_OTR_t* me, inputs_OTR_t* inputs, outputs_OTR_t* outputs) {
	//set any input vars with default values
	
	//set any output vars with default values
	

	
	me->_policy_OTR_Policy_state = POLICY_STATE_OTR_OTR_Policy_s_normal;
	//input policy internal vars
	
	me->tokens = 500;
	
	
}

void OTR_run_via_enforcer(enforcervars_OTR_t* me, inputs_OTR_t* inputs, outputs_OTR_t* outputs) {
	//run the policies in reverse order for the inputs (last policies have highest priority)
	
	 OTR_run_input_enforcer_OTR_Policy(me, inputs);
	

	OTR_run(inputs, outputs);

	//run policies in specified order for outputs
	OTR_run_output_enforcer_OTR_Policy(me, inputs,outputs);
	
}


//input policies

//INPUT POLICY OTR_Policy BEGIN
//This will run the input enforcer for OTR's policy OTR_Policy
void OTR_run_input_enforcer_OTR_Policy(enforcervars_OTR_t* me, inputs_OTR_t* inputs) {
	switch(me->_policy_OTR_Policy_state) {
		case POLICY_STATE_OTR_OTR_Policy_s_normal:
			
			
			break;

		case POLICY_STATE_OTR_OTR_Policy_s_throttled:
			
			
			break;

		
	}
}

//INPUT POLICY OTR_Policy END



//output policies

//OUTPUT POLICY OTR_Policy BEGIN
//This will run the input enforcer for OTR's policy OTR_Policy
void OTR_run_output_enforcer_OTR_Policy(enforcervars_OTR_t* me, inputs_OTR_t* inputs, outputs_OTR_t* outputs) {
	//advance timers
	
	
	//run enforcer
	switch(me->_policy_OTR_Policy_state) {
		case POLICY_STATE_OTR_OTR_Policy_s_normal:
			

			break;

		case POLICY_STATE_OTR_OTR_Policy_s_throttled:
			
			if(outputs->act_MSG) {
				//transition s_throttled -> violation on act_MSG
				//select a transition to solve the problem
				
				//Recovery instructions manually provided.
				outputs->act_MSG = 0;
				
			} 

			break;

		
	}

	//select transition to advance state
	switch(me->_policy_OTR_Policy_state) {
		case POLICY_STATE_OTR_OTR_Policy_s_normal:
			
			if((inputs->act_EXEC && !(outputs->act_MSG)) && me->tokens + CONST_OTR_Policy_Reward <= CONST_OTR_Policy_Max_Cap) {
				//transition s_normal -> s_normal on act_EXEC and !act_MSG and ( tokens + Reward <= Max_Cap )
				me->_policy_OTR_Policy_state = POLICY_STATE_OTR_OTR_Policy_s_normal;
				//set expressions
				
				me->tokens = tokens + Reward;
				break;
			} 
			if((inputs->act_EXEC && !(outputs->act_MSG)) && me->tokens + CONST_OTR_Policy_Reward > CONST_OTR_Policy_Max_Cap) {
				//transition s_normal -> s_normal on act_EXEC and !act_MSG and ( tokens + Reward > Max_Cap )
				me->_policy_OTR_Policy_state = POLICY_STATE_OTR_OTR_Policy_s_normal;
				//set expressions
				
				me->tokens = Max_Cap;
				break;
			} 
			if((inputs->act_EXEC && outputs->act_MSG) && (me->tokens + CONST_OTR_Policy_Reward) - CONST_OTR_Policy_Cost <= CONST_OTR_Policy_Max_Cap) {
				//transition s_normal -> s_normal on act_EXEC and act_MSG and ( tokens + Reward - Cost <= Max_Cap )
				me->_policy_OTR_Policy_state = POLICY_STATE_OTR_OTR_Policy_s_normal;
				//set expressions
				
				me->tokens = tokens + Reward - Cost;
				break;
			} 
			if((inputs->act_EXEC && outputs->act_MSG) && (me->tokens + CONST_OTR_Policy_Reward) - CONST_OTR_Policy_Cost > CONST_OTR_Policy_Max_Cap) {
				//transition s_normal -> s_normal on act_EXEC and act_MSG and ( tokens + Reward - Cost > Max_Cap )
				me->_policy_OTR_Policy_state = POLICY_STATE_OTR_OTR_Policy_s_normal;
				//set expressions
				
				me->tokens = Max_Cap;
				break;
			} 
			if(( !(inputs->act_EXEC) && outputs->act_MSG) && me->tokens - CONST_OTR_Policy_Cost > 0) {
				//transition s_normal -> s_normal on !act_EXEC and act_MSG and ( tokens - Cost > 0 )
				me->_policy_OTR_Policy_state = POLICY_STATE_OTR_OTR_Policy_s_normal;
				//set expressions
				
				me->tokens = tokens - Cost;
				break;
			} 
			if(( !(inputs->act_EXEC) && outputs->act_MSG) && me->tokens - CONST_OTR_Policy_Cost <= 0) {
				//transition s_normal -> s_throttled on !act_EXEC and act_MSG and ( tokens - Cost <= 0 )
				me->_policy_OTR_Policy_state = POLICY_STATE_OTR_OTR_Policy_s_throttled;
				//set expressions
				
				me->tokens = tokens - Cost;
				break;
			} 
			if( !(inputs->act_EXEC) && !(outputs->act_MSG)) {
				//transition s_normal -> s_normal on !act_EXEC and !act_MSG
				me->_policy_OTR_Policy_state = POLICY_STATE_OTR_OTR_Policy_s_normal;
				//set expressions
				
				break;
			} 
			
			//ensure a transition was taken in this state
			assert(false && "OTR_OTR_Policy_s_normal must take a transition"); //if we are still here, then no transition was taken and we are no longer satisfying liveness

			break;

		case POLICY_STATE_OTR_OTR_Policy_s_throttled:
			
			if(inputs->act_EXEC && me->tokens + CONST_OTR_Policy_Reward <= CONST_OTR_Policy_Resume_Threshold) {
				//transition s_throttled -> s_throttled on act_EXEC and ( tokens + Reward <= Resume_Threshold )
				me->_policy_OTR_Policy_state = POLICY_STATE_OTR_OTR_Policy_s_throttled;
				//set expressions
				
				me->tokens = tokens + Reward;
				break;
			} 
			if(inputs->act_EXEC && me->tokens + CONST_OTR_Policy_Reward > CONST_OTR_Policy_Resume_Threshold) {
				//transition s_throttled -> s_normal on act_EXEC and ( tokens + Reward > Resume_Threshold )
				me->_policy_OTR_Policy_state = POLICY_STATE_OTR_OTR_Policy_s_normal;
				//set expressions
				
				me->tokens = tokens + Reward;
				break;
			} 
			if( !(inputs->act_EXEC)) {
				//transition s_throttled -> s_throttled on !act_EXEC
				me->_policy_OTR_Policy_state = POLICY_STATE_OTR_OTR_Policy_s_throttled;
				//set expressions
				
				break;
			} 
			if(outputs->act_MSG) {
				//transition s_throttled -> violation on act_MSG
				me->_policy_OTR_Policy_state = POLICY_STATE_OTR_OTR_Policy_violation;
				//set expressions
				
				break;
			} 
			
			//ensure a transition was taken in this state
			assert(false && "OTR_OTR_Policy_s_throttled must take a transition"); //if we are still here, then no transition was taken and we are no longer satisfying liveness

			break;

		
	}

	//ensure we did not violate (i.e. we did not enter violation state)
	assert(me->_policy_OTR_Policy_state != POLICY_STATE_OTR_OTR_Policy_violation);
}

//OUTPUT POLICY OTR_Policy END



//This function is provided in "F_OTR.c"
//It will check the state of the enforcer monitor code
//It returns one of the following:
//0: currently true (safe)
//1: always true (safe)
//-1: currently false (unsafe)
//-2: always false (unsafe)
//It will need to do some reachability analysis to achieve this

