
//This file should be called cbmc_main_VolatilityHalt.c
//This is autogenerated code. Edit by hand at your peril!

//It can be used with the cbmc model checker
//Call it using the following command: 
//$ cbmc cbmc_main_VolatilityHalt.c F_VolatilityHalt.c


#include "F_VolatilityHalt.h"
#include <stdio.h>
#include <stdint.h>

int main() {


	//I/O and state for VolatilityHalt
	enforcervars_VolatilityHalt_t enf_VolatilityHalt;
    inputs_VolatilityHalt_t inputs_VolatilityHalt;
    outputs_VolatilityHalt_t outputs_VolatilityHalt;

	//set values to known state
    VolatilityHalt_init_all_vars(&enf_VolatilityHalt, &inputs_VolatilityHalt, &outputs_VolatilityHalt);

	//introduce nondeterminism
    //a nondet_xxxxx function name tells cbmc that it could be anything, but must be unique
    //randomise inputs
	inputs_VolatilityHalt.vol_high = nondet_VolatilityHalt_input_0();
	

	//randomise enforcer state, i.e. clock values and position (excepting violation state)
	
	enf_VolatilityHalt._policy_VolatilityCircuitBreaker_state = nondet_VolatilityHalt_enf_VolatilityCircuitBreaker_state() % 1;
	

    //run the enforcer (i.e. tell CBMC to check this out)
	VolatilityHalt_run_via_enforcer(&enf_VolatilityHalt, &inputs_VolatilityHalt, &outputs_VolatilityHalt);

}


void VolatilityHalt_run(inputs_VolatilityHalt_t *inputs, outputs_VolatilityHalt_t *outputs) {
    //randomise controller

    outputs->act_TRADE = nondet_VolatilityHalt_output_0();
	 
}

