
//This file should be called F_VolatilityHalt.c
//This is autogenerated code. Edit by hand at your peril!
#include "F_VolatilityHalt.h"

void VolatilityHalt_init_all_vars(enforcervars_VolatilityHalt_t* me, inputs_VolatilityHalt_t* inputs, outputs_VolatilityHalt_t* outputs) {
	//set any input vars with default values
	
	//set any output vars with default values
	

	
	me->_policy_VolatilityCircuitBreaker_state = POLICY_STATE_VolatilityHalt_VolatilityCircuitBreaker_s0;
	//input policy internal vars
	
	
}

void VolatilityHalt_run_via_enforcer(enforcervars_VolatilityHalt_t* me, inputs_VolatilityHalt_t* inputs, outputs_VolatilityHalt_t* outputs) {
	//run the policies in reverse order for the inputs (last policies have highest priority)
	
	 VolatilityHalt_run_input_enforcer_VolatilityCircuitBreaker(me, inputs);
	

	VolatilityHalt_run(inputs, outputs);

	//run policies in specified order for outputs
	VolatilityHalt_run_output_enforcer_VolatilityCircuitBreaker(me, inputs,outputs);
	
}


//input policies

//INPUT POLICY VolatilityCircuitBreaker BEGIN
//This will run the input enforcer for VolatilityHalt's policy VolatilityCircuitBreaker
void VolatilityHalt_run_input_enforcer_VolatilityCircuitBreaker(enforcervars_VolatilityHalt_t* me, inputs_VolatilityHalt_t* inputs) {
	switch(me->_policy_VolatilityCircuitBreaker_state) {
		case POLICY_STATE_VolatilityHalt_VolatilityCircuitBreaker_s0:
			
			if(inputs->vol_high) {
				//transition s0 -> violation on vol_high
				//select a transition to solve the problem
				
				//Selected non-violation transition "s0 -> s0 on vol_high" which has an equivalent guard, so no action is required
				
			} 
			
			break;

		
	}
}

//INPUT POLICY VolatilityCircuitBreaker END



//output policies

//OUTPUT POLICY VolatilityCircuitBreaker BEGIN
//This will run the input enforcer for VolatilityHalt's policy VolatilityCircuitBreaker
void VolatilityHalt_run_output_enforcer_VolatilityCircuitBreaker(enforcervars_VolatilityHalt_t* me, inputs_VolatilityHalt_t* inputs, outputs_VolatilityHalt_t* outputs) {
	//advance timers
	
	
	//run enforcer
	switch(me->_policy_VolatilityCircuitBreaker_state) {
		case POLICY_STATE_VolatilityHalt_VolatilityCircuitBreaker_s0:
			
			if(inputs->vol_high && outputs->act_TRADE) {
				//transition s0 -> violation on ( vol_high and act_TRADE )
				//select a transition to solve the problem
				
				//Recovery instructions manually provided.
				outputs->act_TRADE = 0;
				
			} 

			break;

		
	}

	//select transition to advance state
	switch(me->_policy_VolatilityCircuitBreaker_state) {
		case POLICY_STATE_VolatilityHalt_VolatilityCircuitBreaker_s0:
			
			if(inputs->vol_high && !(outputs->act_TRADE)) {
				//transition s0 -> s0 on ( vol_high and !act_TRADE )
				me->_policy_VolatilityCircuitBreaker_state = POLICY_STATE_VolatilityHalt_VolatilityCircuitBreaker_s0;
				//set expressions
				
				break;
			} 
			if( !(inputs->vol_high)) {
				//transition s0 -> s0 on ( !vol_high )
				me->_policy_VolatilityCircuitBreaker_state = POLICY_STATE_VolatilityHalt_VolatilityCircuitBreaker_s0;
				//set expressions
				
				break;
			} 
			if(inputs->vol_high && outputs->act_TRADE) {
				//transition s0 -> violation on ( vol_high and act_TRADE )
				me->_policy_VolatilityCircuitBreaker_state = POLICY_STATE_VolatilityHalt_VolatilityCircuitBreaker_violation;
				//set expressions
				
				break;
			} 
			
			//ensure a transition was taken in this state
			assert(false && "VolatilityHalt_VolatilityCircuitBreaker_s0 must take a transition"); //if we are still here, then no transition was taken and we are no longer satisfying liveness

			break;

		
	}

	//ensure we did not violate (i.e. we did not enter violation state)
	assert(me->_policy_VolatilityCircuitBreaker_state != POLICY_STATE_VolatilityHalt_VolatilityCircuitBreaker_violation);
}

//OUTPUT POLICY VolatilityCircuitBreaker END



//This function is provided in "F_VolatilityHalt.c"
//It will check the state of the enforcer monitor code
//It returns one of the following:
//0: currently true (safe)
//1: always true (safe)
//-1: currently false (unsafe)
//-2: always false (unsafe)
//It will need to do some reachability analysis to achieve this

