
//This file should be called F_VolatilityHalt.h
//This is autogenerated code. Edit by hand at your peril!

#include <stdint.h>
#include <stdbool.h>
#include <assert.h>

//the dtimer_t type
typedef uint64_t dtimer_t;

//For each policy, we need an enum type for the state machine

enum VolatilityHalt_policy_VolatilityCircuitBreaker_states { 
	POLICY_STATE_VolatilityHalt_VolatilityCircuitBreaker_s0,
	POLICY_STATE_VolatilityHalt_VolatilityCircuitBreaker_violation 
};


//Inputs to the function VolatilityHalt
typedef struct {
	bool vol_high;
	
} inputs_VolatilityHalt_t;

//Outputs from the function VolatilityHalt
typedef struct {
	bool act_TRADE;
	
} outputs_VolatilityHalt_t;

//enforcer state and vars:
typedef struct {
	enum VolatilityHalt_policy_VolatilityCircuitBreaker_states _policy_VolatilityCircuitBreaker_state;
	//internal vars
	
	
	
} enforcervars_VolatilityHalt_t;



//This function is provided in "F_VolatilityHalt.c"
//It sets up the variable structures to their initial values
void VolatilityHalt_init_all_vars(enforcervars_VolatilityHalt_t* me, inputs_VolatilityHalt_t* inputs, outputs_VolatilityHalt_t* outputs);

//This function is provided in "F_VolatilityHalt.c"
//It will run the synthesised enforcer and call the controller function
void VolatilityHalt_run_via_enforcer(enforcervars_VolatilityHalt_t* me, inputs_VolatilityHalt_t* inputs, outputs_VolatilityHalt_t* outputs);

//This function is provided from the user
//It is the controller function
extern void VolatilityHalt_run(inputs_VolatilityHalt_t* inputs, outputs_VolatilityHalt_t* outputs);

//enforcer functions


//This function is provided in "F_VolatilityHalt.c"
//It will run the input enforcer for VolatilityHalt's policy VolatilityCircuitBreaker
void VolatilityHalt_run_input_enforcer_VolatilityCircuitBreaker(enforcervars_VolatilityHalt_t* me, inputs_VolatilityHalt_t* inputs);

//This function is provided in "F_VolatilityHalt.c"
//It will run the input enforcer for VolatilityHalt's policy VolatilityCircuitBreaker
void VolatilityHalt_run_output_enforcer_VolatilityCircuitBreaker(enforcervars_VolatilityHalt_t* me, inputs_VolatilityHalt_t* inputs, outputs_VolatilityHalt_t* outputs);

//This function is provided in "F_VolatilityHalt.c"
//It will check the state of the enforcer monitor code
//It returns one of the following:
//0: currently true (safe)
//1: always true (safe)
//-1: currently false (unsafe)
//-2: always false (unsafe)
//It will need to do some reachability analysis to achieve this
int VolatilityHalt_check_rv_status_VolatilityCircuitBreaker(enforcervars_VolatilityHalt_t* me);


