
//This file should be called cbmc_main_TradingEnforcer.c
//This is autogenerated code. Edit by hand at your peril!

//It can be used with the cbmc model checker
//Call it using the following command: 
//$ cbmc cbmc_main_TradingEnforcer.c F_TradingEnforcer.c


#include "F_TradingEnforcer.h"
#include <stdio.h>
#include <stdint.h>

int main() {


	//I/O and state for TradingEnforcer
	enforcervars_TradingEnforcer_t enf_TradingEnforcer;
    inputs_TradingEnforcer_t inputs_TradingEnforcer;
    outputs_TradingEnforcer_t outputs_TradingEnforcer;

	//set values to known state
    TradingEnforcer_init_all_vars(&enf_TradingEnforcer, &inputs_TradingEnforcer, &outputs_TradingEnforcer);

	//introduce nondeterminism
    //a nondet_xxxxx function name tells cbmc that it could be anything, but must be unique
    //randomise inputs
	inputs_TradingEnforcer.dd_exceeded = nondet_TradingEnforcer_input_0();
	inputs_TradingEnforcer.is_illiquid = nondet_TradingEnforcer_input_1();
	inputs_TradingEnforcer.will_exceed_limit = nondet_TradingEnforcer_input_2();
	inputs_TradingEnforcer.price_deviates = nondet_TradingEnforcer_input_3();
	

	//randomise enforcer state, i.e. clock values and position (excepting violation state)
	enf_TradingEnforcer.t_window = nondet_TradingEnforcer_enf_Product_of_Product_of_Product_of_Product_of_RateLimit_5_per_1s_and_LatchingKillSwitch_and_RejectDeviantPrice_and_BlockConcentratedBuy_and_BlockIlliquidTrade_0();
	
	
	enf_TradingEnforcer._policy_Product_of_Product_of_Product_of_Product_of_RateLimit_5_per_1s_and_LatchingKillSwitch_and_RejectDeviantPrice_and_BlockConcentratedBuy_and_BlockIlliquidTrade_state = nondet_TradingEnforcer_enf_Product_of_Product_of_Product_of_Product_of_RateLimit_5_per_1s_and_LatchingKillSwitch_and_RejectDeviantPrice_and_BlockConcentratedBuy_and_BlockIlliquidTrade_state() % 6;
	

    //run the enforcer (i.e. tell CBMC to check this out)
	TradingEnforcer_run_via_enforcer(&enf_TradingEnforcer, &inputs_TradingEnforcer, &outputs_TradingEnforcer);

}


void TradingEnforcer_run(inputs_TradingEnforcer_t *inputs, outputs_TradingEnforcer_t *outputs) {
    //randomise controller

    outputs->act_TRADE = nondet_TradingEnforcer_output_0();
	outputs->act_BUY = nondet_TradingEnforcer_output_1();
	 
}

