
//This file should be called cbmc_main_TradingEnforcer.c
//This is autogenerated code. Edit by hand at your peril!

//It can be used with the cbmc model checker
//Call it using the following command: 
//$ cbmc cbmc_main_TradingEnforcer.c F_TradingEnforcer.c


#include "F_TradingEnforcer.h"
#include <stdio.h>
#include <stdint.h>

int main() {


	//I/O and state for TradingEnforcer
	enforcervars_TradingEnforcer_t enf_TradingEnforcer;
    inputs_TradingEnforcer_t inputs_TradingEnforcer;
    outputs_TradingEnforcer_t outputs_TradingEnforcer;

	//set values to known state
    TradingEnforcer_init_all_vars(&enf_TradingEnforcer, &inputs_TradingEnforcer, &outputs_TradingEnforcer);

	//introduce nondeterminism
    //a nondet_xxxxx function name tells cbmc that it could be anything, but must be unique
    //randomise inputs
	inputs_TradingEnforcer.dd_exceeded = nondet_TradingEnforcer_input_0();
	inputs_TradingEnforcer.is_illiquid = nondet_TradingEnforcer_input_1();
	inputs_TradingEnforcer.will_exceed_limit = nondet_TradingEnforcer_input_2();
	inputs_TradingEnforcer.price_deviates = nondet_TradingEnforcer_input_3();
	inputs_TradingEnforcer.act_EXEC = nondet_TradingEnforcer_input_4();
	

	//randomise enforcer state, i.e. clock values and position (excepting violation state)
	enf_TradingEnforcer.t_window = nondet_TradingEnforcer_enf_RateLimit_5_per_1s_0();
	
	
	enf_TradingEnforcer._policy_RateLimit_5_per_1s_state = nondet_TradingEnforcer_enf_RateLimit_5_per_1s_state() % 6;
	
	enf_TradingEnforcer._policy_LatchingKillSwitch_state = nondet_TradingEnforcer_enf_LatchingKillSwitch_state() % 1;
	
	enf_TradingEnforcer._policy_RejectDeviantPrice_state = nondet_TradingEnforcer_enf_RejectDeviantPrice_state() % 1;
	
	enf_TradingEnforcer._policy_BlockConcentratedBuy_state = nondet_TradingEnforcer_enf_BlockConcentratedBuy_state() % 1;
	
	enf_TradingEnforcer._policy_BlockIlliquidTrade_state = nondet_TradingEnforcer_enf_BlockIlliquidTrade_state() % 1;
	enf_TradingEnforcer.tokens = nondet_TradingEnforcer_enf_OTR_Policy_0();
	
	
	
	
	
	enf_TradingEnforcer._policy_OTR_Policy_state = nondet_TradingEnforcer_enf_OTR_Policy_state() % 2;
	enf_TradingEnforcer.c_age = nondet_TradingEnforcer_enf_MQL_Policy_0();
	
	
	enf_TradingEnforcer._policy_MQL_Policy_state = nondet_TradingEnforcer_enf_MQL_Policy_state() % 2;
	enf_TradingEnforcer.last_bid = nondet_TradingEnforcer_enf_NoWash_0();
	enf_TradingEnforcer.last_ask = nondet_TradingEnforcer_enf_NoWash_1();
	
	enf_TradingEnforcer._policy_NoWash_state = nondet_TradingEnforcer_enf_NoWash_state() % 3;
	

    //run the enforcer (i.e. tell CBMC to check this out)
	TradingEnforcer_run_via_enforcer(&enf_TradingEnforcer, &inputs_TradingEnforcer, &outputs_TradingEnforcer);

}


void TradingEnforcer_run(inputs_TradingEnforcer_t *inputs, outputs_TradingEnforcer_t *outputs) {
    //randomise controller

    outputs->act_PLACE = nondet_TradingEnforcer_output_0();
	outputs->act_BUY = nondet_TradingEnforcer_output_1();
	outputs->act_MSG = nondet_TradingEnforcer_output_2();
	outputs->act_CANCEL = nondet_TradingEnforcer_output_3();
	outputs->act_SELL = nondet_TradingEnforcer_output_4();
	outputs->price = nondet_TradingEnforcer_output_5();
	 
}

