
//This file should be called cbmc_main_OTR.c
//This is autogenerated code. Edit by hand at your peril!

//It can be used with the cbmc model checker
//Call it using the following command: 
//$ cbmc cbmc_main_OTR.c F_OTR.c


#include "F_OTR.h"
#include <stdio.h>
#include <stdint.h>

int main() {


	//I/O and state for OTR
	enforcervars_OTR_t enf_OTR;
    inputs_OTR_t inputs_OTR;
    outputs_OTR_t outputs_OTR;

	//set values to known state
    OTR_init_all_vars(&enf_OTR, &inputs_OTR, &outputs_OTR);

	//introduce nondeterminism
    //a nondet_xxxxx function name tells cbmc that it could be anything, but must be unique
    //randomise inputs
	inputs_OTR.act_EXEC = nondet_OTR_input_0();
	

	//randomise enforcer state, i.e. clock values and position (excepting violation state)
	enf_OTR.tokens = nondet_OTR_enf_OTR_Policy_0();
	
	
	
	
	
	enf_OTR._policy_OTR_Policy_state = nondet_OTR_enf_OTR_Policy_state() % 2;
	

    //run the enforcer (i.e. tell CBMC to check this out)
	OTR_run_via_enforcer(&enf_OTR, &inputs_OTR, &outputs_OTR);

}


void OTR_run(inputs_OTR_t *inputs, outputs_OTR_t *outputs) {
    //randomise controller

    outputs->act_MSG = nondet_OTR_output_0();
	 
}

