
//This file should be called F_OTR.h
//This is autogenerated code. Edit by hand at your peril!

#include <stdint.h>
#include <stdbool.h>
#include <assert.h>

//the dtimer_t type
typedef uint64_t dtimer_t;

//For each policy, we need an enum type for the state machine

enum OTR_policy_OTR_Policy_states { 
	POLICY_STATE_OTR_OTR_Policy_s_normal, 
	POLICY_STATE_OTR_OTR_Policy_s_throttled,
	POLICY_STATE_OTR_OTR_Policy_violation 
};


//Inputs to the function OTR
typedef struct {
	bool act_EXEC;
	
} inputs_OTR_t;

//Outputs from the function OTR
typedef struct {
	bool act_MSG;
	
} outputs_OTR_t;

//enforcer state and vars:
typedef struct {
	enum OTR_policy_OTR_Policy_states _policy_OTR_Policy_state;
	//internal vars
	int32_t tokens;
	
	
	
} enforcervars_OTR_t;


#define CONST_OTR_Policy_Max_Cap 500
#define CONST_OTR_Policy_Reward 50
#define CONST_OTR_Policy_Cost 1
#define CONST_OTR_Policy_Resume_Threshold 10


//This function is provided in "F_OTR.c"
//It sets up the variable structures to their initial values
void OTR_init_all_vars(enforcervars_OTR_t* me, inputs_OTR_t* inputs, outputs_OTR_t* outputs);

//This function is provided in "F_OTR.c"
//It will run the synthesised enforcer and call the controller function
void OTR_run_via_enforcer(enforcervars_OTR_t* me, inputs_OTR_t* inputs, outputs_OTR_t* outputs);

//This function is provided from the user
//It is the controller function
extern void OTR_run(inputs_OTR_t* inputs, outputs_OTR_t* outputs);

//enforcer functions


//This function is provided in "F_OTR.c"
//It will run the input enforcer for OTR's policy OTR_Policy
void OTR_run_input_enforcer_OTR_Policy(enforcervars_OTR_t* me, inputs_OTR_t* inputs);

//This function is provided in "F_OTR.c"
//It will run the input enforcer for OTR's policy OTR_Policy
void OTR_run_output_enforcer_OTR_Policy(enforcervars_OTR_t* me, inputs_OTR_t* inputs, outputs_OTR_t* outputs);

//This function is provided in "F_OTR.c"
//It will check the state of the enforcer monitor code
//It returns one of the following:
//0: currently true (safe)
//1: always true (safe)
//-1: currently false (unsafe)
//-2: always false (unsafe)
//It will need to do some reachability analysis to achieve this
int OTR_check_rv_status_OTR_Policy(enforcervars_OTR_t* me);


