
//This file should be called cbmc_main_OrderRateLimit.c
//This is autogenerated code. Edit by hand at your peril!

//It can be used with the cbmc model checker
//Call it using the following command: 
//$ cbmc cbmc_main_OrderRateLimit.c F_OrderRateLimit.c


#include "F_OrderRateLimit.h"
#include <stdio.h>
#include <stdint.h>

int main() {


	//I/O and state for OrderRateLimit
	enforcervars_OrderRateLimit_t enf_OrderRateLimit;
    inputs_OrderRateLimit_t inputs_OrderRateLimit;
    outputs_OrderRateLimit_t outputs_OrderRateLimit;

	//set values to known state
    OrderRateLimit_init_all_vars(&enf_OrderRateLimit, &inputs_OrderRateLimit, &outputs_OrderRateLimit);

	//introduce nondeterminism
    //a nondet_xxxxx function name tells cbmc that it could be anything, but must be unique
    //randomise inputs
	

	//randomise enforcer state, i.e. clock values and position (excepting violation state)
	enf_OrderRateLimit.t_window = nondet_OrderRateLimit_enf_RateLimit_5_per_1s_0();
	
	
	enf_OrderRateLimit._policy_RateLimit_5_per_1s_state = nondet_OrderRateLimit_enf_RateLimit_5_per_1s_state() % 6;
	

    //run the enforcer (i.e. tell CBMC to check this out)
	OrderRateLimit_run_via_enforcer(&enf_OrderRateLimit, &inputs_OrderRateLimit, &outputs_OrderRateLimit);

}


void OrderRateLimit_run(inputs_OrderRateLimit_t *inputs, outputs_OrderRateLimit_t *outputs) {
    //randomise controller

    outputs->act_TRADE = nondet_OrderRateLimit_output_0();
	 
}

