
//This file should be called F_OrderRateLimit.h
//This is autogenerated code. Edit by hand at your peril!

#include <stdint.h>
#include <stdbool.h>
#include <assert.h>

//the dtimer_t type
typedef uint64_t dtimer_t;

//For each policy, we need an enum type for the state machine

enum OrderRateLimit_policy_RateLimit_5_per_1s_states { 
	POLICY_STATE_OrderRateLimit_RateLimit_5_per_1s_s0, 
	POLICY_STATE_OrderRateLimit_RateLimit_5_per_1s_s1, 
	POLICY_STATE_OrderRateLimit_RateLimit_5_per_1s_s2, 
	POLICY_STATE_OrderRateLimit_RateLimit_5_per_1s_s3, 
	POLICY_STATE_OrderRateLimit_RateLimit_5_per_1s_s4, 
	POLICY_STATE_OrderRateLimit_RateLimit_5_per_1s_s5,
	POLICY_STATE_OrderRateLimit_RateLimit_5_per_1s_violation 
};


//Inputs to the function OrderRateLimit
typedef struct {
	
} inputs_OrderRateLimit_t;

//Outputs from the function OrderRateLimit
typedef struct {
	bool act_TRADE;
	
} outputs_OrderRateLimit_t;

//enforcer state and vars:
typedef struct {
	enum OrderRateLimit_policy_RateLimit_5_per_1s_states _policy_RateLimit_5_per_1s_state;
	//internal vars
	dtimer_t t_window;
	
	
	
} enforcervars_OrderRateLimit_t;


#define CONST_RateLimit_5_per_1s_T_WINDOW 5


//This function is provided in "F_OrderRateLimit.c"
//It sets up the variable structures to their initial values
void OrderRateLimit_init_all_vars(enforcervars_OrderRateLimit_t* me, inputs_OrderRateLimit_t* inputs, outputs_OrderRateLimit_t* outputs);

//This function is provided in "F_OrderRateLimit.c"
//It will run the synthesised enforcer and call the controller function
void OrderRateLimit_run_via_enforcer(enforcervars_OrderRateLimit_t* me, inputs_OrderRateLimit_t* inputs, outputs_OrderRateLimit_t* outputs);

//This function is provided from the user
//It is the controller function
extern void OrderRateLimit_run(inputs_OrderRateLimit_t* inputs, outputs_OrderRateLimit_t* outputs);

//enforcer functions


//This function is provided in "F_OrderRateLimit.c"
//It will run the input enforcer for OrderRateLimit's policy RateLimit_5_per_1s
void OrderRateLimit_run_input_enforcer_RateLimit_5_per_1s(enforcervars_OrderRateLimit_t* me, inputs_OrderRateLimit_t* inputs);

//This function is provided in "F_OrderRateLimit.c"
//It will run the input enforcer for OrderRateLimit's policy RateLimit_5_per_1s
void OrderRateLimit_run_output_enforcer_RateLimit_5_per_1s(enforcervars_OrderRateLimit_t* me, inputs_OrderRateLimit_t* inputs, outputs_OrderRateLimit_t* outputs);

//This function is provided in "F_OrderRateLimit.c"
//It will check the state of the enforcer monitor code
//It returns one of the following:
//0: currently true (safe)
//1: always true (safe)
//-1: currently false (unsafe)
//-2: always false (unsafe)
//It will need to do some reachability analysis to achieve this
int OrderRateLimit_check_rv_status_RateLimit_5_per_1s(enforcervars_OrderRateLimit_t* me);


