
//This file should be called F_OrderRateLimit.c
//This is autogenerated code. Edit by hand at your peril!
#include "F_OrderRateLimit.h"

void OrderRateLimit_init_all_vars(enforcervars_OrderRateLimit_t* me, inputs_OrderRateLimit_t* inputs, outputs_OrderRateLimit_t* outputs) {
	//set any input vars with default values
	
	//set any output vars with default values
	

	
	me->_policy_RateLimit_5_per_1s_state = POLICY_STATE_OrderRateLimit_RateLimit_5_per_1s_s0;
	//input policy internal vars
	
	me->t_window = 0;
	
	
}

void OrderRateLimit_run_via_enforcer(enforcervars_OrderRateLimit_t* me, inputs_OrderRateLimit_t* inputs, outputs_OrderRateLimit_t* outputs) {
	//run the policies in reverse order for the inputs (last policies have highest priority)
	
	 OrderRateLimit_run_input_enforcer_RateLimit_5_per_1s(me, inputs);
	

	OrderRateLimit_run(inputs, outputs);

	//run policies in specified order for outputs
	OrderRateLimit_run_output_enforcer_RateLimit_5_per_1s(me, inputs,outputs);
	
}


//input policies

//INPUT POLICY RateLimit_5_per_1s BEGIN
//This will run the input enforcer for OrderRateLimit's policy RateLimit_5_per_1s
void OrderRateLimit_run_input_enforcer_RateLimit_5_per_1s(enforcervars_OrderRateLimit_t* me, inputs_OrderRateLimit_t* inputs) {
	switch(me->_policy_RateLimit_5_per_1s_state) {
		case POLICY_STATE_OrderRateLimit_RateLimit_5_per_1s_s0:
			
			
			break;

		case POLICY_STATE_OrderRateLimit_RateLimit_5_per_1s_s1:
			
			
			break;

		case POLICY_STATE_OrderRateLimit_RateLimit_5_per_1s_s2:
			
			
			break;

		case POLICY_STATE_OrderRateLimit_RateLimit_5_per_1s_s3:
			
			
			break;

		case POLICY_STATE_OrderRateLimit_RateLimit_5_per_1s_s4:
			
			
			break;

		case POLICY_STATE_OrderRateLimit_RateLimit_5_per_1s_s5:
			
			if(me->t_window < CONST_RateLimit_5_per_1s_T_WINDOW) {
				//transition s5 -> violation on t_window < T_WINDOW
				//select a transition to solve the problem
				
				//Recovery instructions manually provided.
				
			} 
			
			break;

		
	}
}

//INPUT POLICY RateLimit_5_per_1s END



//output policies

//OUTPUT POLICY RateLimit_5_per_1s BEGIN
//This will run the input enforcer for OrderRateLimit's policy RateLimit_5_per_1s
void OrderRateLimit_run_output_enforcer_RateLimit_5_per_1s(enforcervars_OrderRateLimit_t* me, inputs_OrderRateLimit_t* inputs, outputs_OrderRateLimit_t* outputs) {
	//advance timers
	
	me->t_window++;
	
	//run enforcer
	switch(me->_policy_RateLimit_5_per_1s_state) {
		case POLICY_STATE_OrderRateLimit_RateLimit_5_per_1s_s0:
			

			break;

		case POLICY_STATE_OrderRateLimit_RateLimit_5_per_1s_s1:
			

			break;

		case POLICY_STATE_OrderRateLimit_RateLimit_5_per_1s_s2:
			

			break;

		case POLICY_STATE_OrderRateLimit_RateLimit_5_per_1s_s3:
			

			break;

		case POLICY_STATE_OrderRateLimit_RateLimit_5_per_1s_s4:
			

			break;

		case POLICY_STATE_OrderRateLimit_RateLimit_5_per_1s_s5:
			
			if(outputs->act_TRADE && me->t_window < CONST_RateLimit_5_per_1s_T_WINDOW) {
				//transition s5 -> violation on ( act_TRADE and t_window < T_WINDOW )
				//select a transition to solve the problem
				
				//Recovery instructions manually provided.
				outputs->act_TRADE = 0;
				
			} 

			break;

		
	}

	//select transition to advance state
	switch(me->_policy_RateLimit_5_per_1s_state) {
		case POLICY_STATE_OrderRateLimit_RateLimit_5_per_1s_s0:
			
			if(outputs->act_TRADE) {
				//transition s0 -> s1 on ( act_TRADE )
				me->_policy_RateLimit_5_per_1s_state = POLICY_STATE_OrderRateLimit_RateLimit_5_per_1s_s1;
				//set expressions
				
				me->t_window = 0;
				break;
			} 
			if( !(outputs->act_TRADE)) {
				//transition s0 -> s0 on ( !act_TRADE )
				me->_policy_RateLimit_5_per_1s_state = POLICY_STATE_OrderRateLimit_RateLimit_5_per_1s_s0;
				//set expressions
				
				break;
			} 
			
			//ensure a transition was taken in this state
			assert(false && "OrderRateLimit_RateLimit_5_per_1s_s0 must take a transition"); //if we are still here, then no transition was taken and we are no longer satisfying liveness

			break;

		case POLICY_STATE_OrderRateLimit_RateLimit_5_per_1s_s1:
			
			if(outputs->act_TRADE && me->t_window < CONST_RateLimit_5_per_1s_T_WINDOW) {
				//transition s1 -> s2 on ( act_TRADE and t_window < T_WINDOW )
				me->_policy_RateLimit_5_per_1s_state = POLICY_STATE_OrderRateLimit_RateLimit_5_per_1s_s2;
				//set expressions
				
				break;
			} 
			if(outputs->act_TRADE && me->t_window >= CONST_RateLimit_5_per_1s_T_WINDOW) {
				//transition s1 -> s1 on ( act_TRADE and t_window >= T_WINDOW )
				me->_policy_RateLimit_5_per_1s_state = POLICY_STATE_OrderRateLimit_RateLimit_5_per_1s_s1;
				//set expressions
				
				me->t_window = 0;
				break;
			} 
			if( !(outputs->act_TRADE)) {
				//transition s1 -> s1 on ( !act_TRADE )
				me->_policy_RateLimit_5_per_1s_state = POLICY_STATE_OrderRateLimit_RateLimit_5_per_1s_s1;
				//set expressions
				
				break;
			} 
			
			//ensure a transition was taken in this state
			assert(false && "OrderRateLimit_RateLimit_5_per_1s_s1 must take a transition"); //if we are still here, then no transition was taken and we are no longer satisfying liveness

			break;

		case POLICY_STATE_OrderRateLimit_RateLimit_5_per_1s_s2:
			
			if(outputs->act_TRADE && me->t_window < CONST_RateLimit_5_per_1s_T_WINDOW) {
				//transition s2 -> s3 on ( act_TRADE and t_window < T_WINDOW )
				me->_policy_RateLimit_5_per_1s_state = POLICY_STATE_OrderRateLimit_RateLimit_5_per_1s_s3;
				//set expressions
				
				break;
			} 
			if(outputs->act_TRADE && me->t_window >= CONST_RateLimit_5_per_1s_T_WINDOW) {
				//transition s2 -> s1 on ( act_TRADE and t_window >= T_WINDOW )
				me->_policy_RateLimit_5_per_1s_state = POLICY_STATE_OrderRateLimit_RateLimit_5_per_1s_s1;
				//set expressions
				
				me->t_window = 0;
				break;
			} 
			if( !(outputs->act_TRADE)) {
				//transition s2 -> s2 on ( !act_TRADE )
				me->_policy_RateLimit_5_per_1s_state = POLICY_STATE_OrderRateLimit_RateLimit_5_per_1s_s2;
				//set expressions
				
				break;
			} 
			
			//ensure a transition was taken in this state
			assert(false && "OrderRateLimit_RateLimit_5_per_1s_s2 must take a transition"); //if we are still here, then no transition was taken and we are no longer satisfying liveness

			break;

		case POLICY_STATE_OrderRateLimit_RateLimit_5_per_1s_s3:
			
			if(outputs->act_TRADE && me->t_window < CONST_RateLimit_5_per_1s_T_WINDOW) {
				//transition s3 -> s4 on ( act_TRADE and t_window < T_WINDOW )
				me->_policy_RateLimit_5_per_1s_state = POLICY_STATE_OrderRateLimit_RateLimit_5_per_1s_s4;
				//set expressions
				
				break;
			} 
			if(outputs->act_TRADE && me->t_window >= CONST_RateLimit_5_per_1s_T_WINDOW) {
				//transition s3 -> s1 on ( act_TRADE and t_window >= T_WINDOW )
				me->_policy_RateLimit_5_per_1s_state = POLICY_STATE_OrderRateLimit_RateLimit_5_per_1s_s1;
				//set expressions
				
				me->t_window = 0;
				break;
			} 
			if( !(outputs->act_TRADE)) {
				//transition s3 -> s3 on ( !act_TRADE )
				me->_policy_RateLimit_5_per_1s_state = POLICY_STATE_OrderRateLimit_RateLimit_5_per_1s_s3;
				//set expressions
				
				break;
			} 
			
			//ensure a transition was taken in this state
			assert(false && "OrderRateLimit_RateLimit_5_per_1s_s3 must take a transition"); //if we are still here, then no transition was taken and we are no longer satisfying liveness

			break;

		case POLICY_STATE_OrderRateLimit_RateLimit_5_per_1s_s4:
			
			if(outputs->act_TRADE && me->t_window < CONST_RateLimit_5_per_1s_T_WINDOW) {
				//transition s4 -> s5 on ( act_TRADE and t_window < T_WINDOW )
				me->_policy_RateLimit_5_per_1s_state = POLICY_STATE_OrderRateLimit_RateLimit_5_per_1s_s5;
				//set expressions
				
				break;
			} 
			if(outputs->act_TRADE && me->t_window >= CONST_RateLimit_5_per_1s_T_WINDOW) {
				//transition s4 -> s1 on ( act_TRADE and t_window >= T_WINDOW )
				me->_policy_RateLimit_5_per_1s_state = POLICY_STATE_OrderRateLimit_RateLimit_5_per_1s_s1;
				//set expressions
				
				me->t_window = 0;
				break;
			} 
			if( !(outputs->act_TRADE)) {
				//transition s4 -> s4 on ( !act_TRADE )
				me->_policy_RateLimit_5_per_1s_state = POLICY_STATE_OrderRateLimit_RateLimit_5_per_1s_s4;
				//set expressions
				
				break;
			} 
			
			//ensure a transition was taken in this state
			assert(false && "OrderRateLimit_RateLimit_5_per_1s_s4 must take a transition"); //if we are still here, then no transition was taken and we are no longer satisfying liveness

			break;

		case POLICY_STATE_OrderRateLimit_RateLimit_5_per_1s_s5:
			
			if(outputs->act_TRADE && me->t_window >= CONST_RateLimit_5_per_1s_T_WINDOW) {
				//transition s5 -> s1 on ( act_TRADE and t_window >= T_WINDOW )
				me->_policy_RateLimit_5_per_1s_state = POLICY_STATE_OrderRateLimit_RateLimit_5_per_1s_s1;
				//set expressions
				
				me->t_window = 0;
				break;
			} 
			if( !(outputs->act_TRADE)) {
				//transition s5 -> s5 on ( !act_TRADE )
				me->_policy_RateLimit_5_per_1s_state = POLICY_STATE_OrderRateLimit_RateLimit_5_per_1s_s5;
				//set expressions
				
				break;
			} 
			if(outputs->act_TRADE && me->t_window < CONST_RateLimit_5_per_1s_T_WINDOW) {
				//transition s5 -> violation on ( act_TRADE and t_window < T_WINDOW )
				me->_policy_RateLimit_5_per_1s_state = POLICY_STATE_OrderRateLimit_RateLimit_5_per_1s_violation;
				//set expressions
				
				break;
			} 
			
			//ensure a transition was taken in this state
			assert(false && "OrderRateLimit_RateLimit_5_per_1s_s5 must take a transition"); //if we are still here, then no transition was taken and we are no longer satisfying liveness

			break;

		
	}

	//ensure we did not violate (i.e. we did not enter violation state)
	assert(me->_policy_RateLimit_5_per_1s_state != POLICY_STATE_OrderRateLimit_RateLimit_5_per_1s_violation);
}

//OUTPUT POLICY RateLimit_5_per_1s END



//This function is provided in "F_OrderRateLimit.c"
//It will check the state of the enforcer monitor code
//It returns one of the following:
//0: currently true (safe)
//1: always true (safe)
//-1: currently false (unsafe)
//-2: always false (unsafe)
//It will need to do some reachability analysis to achieve this

