
//This file should be called cbmc_main_PriceCollar.c
//This is autogenerated code. Edit by hand at your peril!

//It can be used with the cbmc model checker
//Call it using the following command: 
//$ cbmc cbmc_main_PriceCollar.c F_PriceCollar.c


#include "F_PriceCollar.h"
#include <stdio.h>
#include <stdint.h>

int main() {


	//I/O and state for PriceCollar
	enforcervars_PriceCollar_t enf_PriceCollar;
    inputs_PriceCollar_t inputs_PriceCollar;
    outputs_PriceCollar_t outputs_PriceCollar;

	//set values to known state
    PriceCollar_init_all_vars(&enf_PriceCollar, &inputs_PriceCollar, &outputs_PriceCollar);

	//introduce nondeterminism
    //a nondet_xxxxx function name tells cbmc that it could be anything, but must be unique
    //randomise inputs
	inputs_PriceCollar.price_deviates = nondet_PriceCollar_input_0();
	

	//randomise enforcer state, i.e. clock values and position (excepting violation state)
	
	enf_PriceCollar._policy_RejectDeviantPrice_state = nondet_PriceCollar_enf_RejectDeviantPrice_state() % 1;
	

    //run the enforcer (i.e. tell CBMC to check this out)
	PriceCollar_run_via_enforcer(&enf_PriceCollar, &inputs_PriceCollar, &outputs_PriceCollar);

}


void PriceCollar_run(inputs_PriceCollar_t *inputs, outputs_PriceCollar_t *outputs) {
    //randomise controller

    outputs->act_TRADE = nondet_PriceCollar_output_0();
	 
}

