
//This file should be called F_PriceCollar.c
//This is autogenerated code. Edit by hand at your peril!
#include "F_PriceCollar.h"

void PriceCollar_init_all_vars(enforcervars_PriceCollar_t* me, inputs_PriceCollar_t* inputs, outputs_PriceCollar_t* outputs) {
	//set any input vars with default values
	
	//set any output vars with default values
	

	
	me->_policy_RejectDeviantPrice_state = POLICY_STATE_PriceCollar_RejectDeviantPrice_s0;
	//input policy internal vars
	
	
}

void PriceCollar_run_via_enforcer(enforcervars_PriceCollar_t* me, inputs_PriceCollar_t* inputs, outputs_PriceCollar_t* outputs) {
	//run the policies in reverse order for the inputs (last policies have highest priority)
	
	 PriceCollar_run_input_enforcer_RejectDeviantPrice(me, inputs);
	

	PriceCollar_run(inputs, outputs);

	//run policies in specified order for outputs
	PriceCollar_run_output_enforcer_RejectDeviantPrice(me, inputs,outputs);
	
}


//input policies

//INPUT POLICY RejectDeviantPrice BEGIN
//This will run the input enforcer for PriceCollar's policy RejectDeviantPrice
void PriceCollar_run_input_enforcer_RejectDeviantPrice(enforcervars_PriceCollar_t* me, inputs_PriceCollar_t* inputs) {
	switch(me->_policy_RejectDeviantPrice_state) {
		case POLICY_STATE_PriceCollar_RejectDeviantPrice_s0:
			
			if(inputs->price_deviates) {
				//transition s0 -> violation on price_deviates
				//select a transition to solve the problem
				
				//Selected non-violation transition "s0 -> s0 on price_deviates" which has an equivalent guard, so no action is required
				
			} 
			
			break;

		
	}
}

//INPUT POLICY RejectDeviantPrice END



//output policies

//OUTPUT POLICY RejectDeviantPrice BEGIN
//This will run the input enforcer for PriceCollar's policy RejectDeviantPrice
void PriceCollar_run_output_enforcer_RejectDeviantPrice(enforcervars_PriceCollar_t* me, inputs_PriceCollar_t* inputs, outputs_PriceCollar_t* outputs) {
	//advance timers
	
	
	//run enforcer
	switch(me->_policy_RejectDeviantPrice_state) {
		case POLICY_STATE_PriceCollar_RejectDeviantPrice_s0:
			
			if(inputs->price_deviates && outputs->act_TRADE) {
				//transition s0 -> violation on ( price_deviates and act_TRADE )
				//select a transition to solve the problem
				
				//Recovery instructions manually provided.
				outputs->act_TRADE = 0;
				
			} 

			break;

		
	}

	//select transition to advance state
	switch(me->_policy_RejectDeviantPrice_state) {
		case POLICY_STATE_PriceCollar_RejectDeviantPrice_s0:
			
			if(inputs->price_deviates && !(outputs->act_TRADE)) {
				//transition s0 -> s0 on ( price_deviates and !act_TRADE )
				me->_policy_RejectDeviantPrice_state = POLICY_STATE_PriceCollar_RejectDeviantPrice_s0;
				//set expressions
				
				break;
			} 
			if( !(inputs->price_deviates)) {
				//transition s0 -> s0 on ( !price_deviates )
				me->_policy_RejectDeviantPrice_state = POLICY_STATE_PriceCollar_RejectDeviantPrice_s0;
				//set expressions
				
				break;
			} 
			if(inputs->price_deviates && outputs->act_TRADE) {
				//transition s0 -> violation on ( price_deviates and act_TRADE )
				me->_policy_RejectDeviantPrice_state = POLICY_STATE_PriceCollar_RejectDeviantPrice_violation;
				//set expressions
				
				break;
			} 
			
			//ensure a transition was taken in this state
			assert(false && "PriceCollar_RejectDeviantPrice_s0 must take a transition"); //if we are still here, then no transition was taken and we are no longer satisfying liveness

			break;

		
	}

	//ensure we did not violate (i.e. we did not enter violation state)
	assert(me->_policy_RejectDeviantPrice_state != POLICY_STATE_PriceCollar_RejectDeviantPrice_violation);
}

//OUTPUT POLICY RejectDeviantPrice END



//This function is provided in "F_PriceCollar.c"
//It will check the state of the enforcer monitor code
//It returns one of the following:
//0: currently true (safe)
//1: always true (safe)
//-1: currently false (unsafe)
//-2: always false (unsafe)
//It will need to do some reachability analysis to achieve this

