
//This file should be called F_PriceCollar.h
//This is autogenerated code. Edit by hand at your peril!

#include <stdint.h>
#include <stdbool.h>
#include <assert.h>

//the dtimer_t type
typedef uint64_t dtimer_t;

//For each policy, we need an enum type for the state machine

enum PriceCollar_policy_RejectDeviantPrice_states { 
	POLICY_STATE_PriceCollar_RejectDeviantPrice_s0,
	POLICY_STATE_PriceCollar_RejectDeviantPrice_violation 
};


//Inputs to the function PriceCollar
typedef struct {
	bool price_deviates;
	
} inputs_PriceCollar_t;

//Outputs from the function PriceCollar
typedef struct {
	bool act_TRADE;
	
} outputs_PriceCollar_t;

//enforcer state and vars:
typedef struct {
	enum PriceCollar_policy_RejectDeviantPrice_states _policy_RejectDeviantPrice_state;
	//internal vars
	
	
	
} enforcervars_PriceCollar_t;



//This function is provided in "F_PriceCollar.c"
//It sets up the variable structures to their initial values
void PriceCollar_init_all_vars(enforcervars_PriceCollar_t* me, inputs_PriceCollar_t* inputs, outputs_PriceCollar_t* outputs);

//This function is provided in "F_PriceCollar.c"
//It will run the synthesised enforcer and call the controller function
void PriceCollar_run_via_enforcer(enforcervars_PriceCollar_t* me, inputs_PriceCollar_t* inputs, outputs_PriceCollar_t* outputs);

//This function is provided from the user
//It is the controller function
extern void PriceCollar_run(inputs_PriceCollar_t* inputs, outputs_PriceCollar_t* outputs);

//enforcer functions


//This function is provided in "F_PriceCollar.c"
//It will run the input enforcer for PriceCollar's policy RejectDeviantPrice
void PriceCollar_run_input_enforcer_RejectDeviantPrice(enforcervars_PriceCollar_t* me, inputs_PriceCollar_t* inputs);

//This function is provided in "F_PriceCollar.c"
//It will run the input enforcer for PriceCollar's policy RejectDeviantPrice
void PriceCollar_run_output_enforcer_RejectDeviantPrice(enforcervars_PriceCollar_t* me, inputs_PriceCollar_t* inputs, outputs_PriceCollar_t* outputs);

//This function is provided in "F_PriceCollar.c"
//It will check the state of the enforcer monitor code
//It returns one of the following:
//0: currently true (safe)
//1: always true (safe)
//-1: currently false (unsafe)
//-2: always false (unsafe)
//It will need to do some reachability analysis to achieve this
int PriceCollar_check_rv_status_RejectDeviantPrice(enforcervars_PriceCollar_t* me);


