
//This file should be called cbmc_main_Liquidity.c
//This is autogenerated code. Edit by hand at your peril!

//It can be used with the cbmc model checker
//Call it using the following command: 
//$ cbmc cbmc_main_Liquidity.c F_Liquidity.c


#include "F_Liquidity.h"
#include <stdio.h>
#include <stdint.h>

int main() {


	//I/O and state for Liquidity
	enforcervars_Liquidity_t enf_Liquidity;
    inputs_Liquidity_t inputs_Liquidity;
    outputs_Liquidity_t outputs_Liquidity;

	//set values to known state
    Liquidity_init_all_vars(&enf_Liquidity, &inputs_Liquidity, &outputs_Liquidity);

	//introduce nondeterminism
    //a nondet_xxxxx function name tells cbmc that it could be anything, but must be unique
    //randomise inputs
	inputs_Liquidity.is_illiquid = nondet_Liquidity_input_0();
	

	//randomise enforcer state, i.e. clock values and position (excepting violation state)
	
	enf_Liquidity._policy_BlockIlliquidTrade_state = nondet_Liquidity_enf_BlockIlliquidTrade_state() % 1;
	

    //run the enforcer (i.e. tell CBMC to check this out)
	Liquidity_run_via_enforcer(&enf_Liquidity, &inputs_Liquidity, &outputs_Liquidity);

}


void Liquidity_run(inputs_Liquidity_t *inputs, outputs_Liquidity_t *outputs) {
    //randomise controller

    outputs->act_TRADE = nondet_Liquidity_output_0();
	 
}

