
//This file should be called F_Liquidity.h
//This is autogenerated code. Edit by hand at your peril!

#include <stdint.h>
#include <stdbool.h>
#include <assert.h>

//the dtimer_t type
typedef uint64_t dtimer_t;

//For each policy, we need an enum type for the state machine

enum Liquidity_policy_BlockIlliquidTrade_states { 
	POLICY_STATE_Liquidity_BlockIlliquidTrade_s0,
	POLICY_STATE_Liquidity_BlockIlliquidTrade_violation 
};


//Inputs to the function Liquidity
typedef struct {
	bool is_illiquid;
	
} inputs_Liquidity_t;

//Outputs from the function Liquidity
typedef struct {
	bool act_TRADE;
	
} outputs_Liquidity_t;

//enforcer state and vars:
typedef struct {
	enum Liquidity_policy_BlockIlliquidTrade_states _policy_BlockIlliquidTrade_state;
	//internal vars
	
	
	
} enforcervars_Liquidity_t;



//This function is provided in "F_Liquidity.c"
//It sets up the variable structures to their initial values
void Liquidity_init_all_vars(enforcervars_Liquidity_t* me, inputs_Liquidity_t* inputs, outputs_Liquidity_t* outputs);

//This function is provided in "F_Liquidity.c"
//It will run the synthesised enforcer and call the controller function
void Liquidity_run_via_enforcer(enforcervars_Liquidity_t* me, inputs_Liquidity_t* inputs, outputs_Liquidity_t* outputs);

//This function is provided from the user
//It is the controller function
extern void Liquidity_run(inputs_Liquidity_t* inputs, outputs_Liquidity_t* outputs);

//enforcer functions


//This function is provided in "F_Liquidity.c"
//It will run the input enforcer for Liquidity's policy BlockIlliquidTrade
void Liquidity_run_input_enforcer_BlockIlliquidTrade(enforcervars_Liquidity_t* me, inputs_Liquidity_t* inputs);

//This function is provided in "F_Liquidity.c"
//It will run the input enforcer for Liquidity's policy BlockIlliquidTrade
void Liquidity_run_output_enforcer_BlockIlliquidTrade(enforcervars_Liquidity_t* me, inputs_Liquidity_t* inputs, outputs_Liquidity_t* outputs);

//This function is provided in "F_Liquidity.c"
//It will check the state of the enforcer monitor code
//It returns one of the following:
//0: currently true (safe)
//1: always true (safe)
//-1: currently false (unsafe)
//-2: always false (unsafe)
//It will need to do some reachability analysis to achieve this
int Liquidity_check_rv_status_BlockIlliquidTrade(enforcervars_Liquidity_t* me);


