
//This file should be called F_Liquidity.c
//This is autogenerated code. Edit by hand at your peril!
#include "F_Liquidity.h"

void Liquidity_init_all_vars(enforcervars_Liquidity_t* me, inputs_Liquidity_t* inputs, outputs_Liquidity_t* outputs) {
	//set any input vars with default values
	
	//set any output vars with default values
	

	
	me->_policy_BlockIlliquidTrade_state = POLICY_STATE_Liquidity_BlockIlliquidTrade_s0;
	//input policy internal vars
	
	
}

void Liquidity_run_via_enforcer(enforcervars_Liquidity_t* me, inputs_Liquidity_t* inputs, outputs_Liquidity_t* outputs) {
	//run the policies in reverse order for the inputs (last policies have highest priority)
	
	 Liquidity_run_input_enforcer_BlockIlliquidTrade(me, inputs);
	

	Liquidity_run(inputs, outputs);

	//run policies in specified order for outputs
	Liquidity_run_output_enforcer_BlockIlliquidTrade(me, inputs,outputs);
	
}


//input policies

//INPUT POLICY BlockIlliquidTrade BEGIN
//This will run the input enforcer for Liquidity's policy BlockIlliquidTrade
void Liquidity_run_input_enforcer_BlockIlliquidTrade(enforcervars_Liquidity_t* me, inputs_Liquidity_t* inputs) {
	switch(me->_policy_BlockIlliquidTrade_state) {
		case POLICY_STATE_Liquidity_BlockIlliquidTrade_s0:
			
			if(inputs->is_illiquid) {
				//transition s0 -> violation on is_illiquid
				//select a transition to solve the problem
				
				//Selected non-violation transition "s0 -> s0 on is_illiquid" which has an equivalent guard, so no action is required
				
			} 
			
			break;

		
	}
}

//INPUT POLICY BlockIlliquidTrade END



//output policies

//OUTPUT POLICY BlockIlliquidTrade BEGIN
//This will run the input enforcer for Liquidity's policy BlockIlliquidTrade
void Liquidity_run_output_enforcer_BlockIlliquidTrade(enforcervars_Liquidity_t* me, inputs_Liquidity_t* inputs, outputs_Liquidity_t* outputs) {
	//advance timers
	
	
	//run enforcer
	switch(me->_policy_BlockIlliquidTrade_state) {
		case POLICY_STATE_Liquidity_BlockIlliquidTrade_s0:
			
			if(inputs->is_illiquid && outputs->act_TRADE) {
				//transition s0 -> violation on ( is_illiquid and act_TRADE )
				//select a transition to solve the problem
				
				//Recovery instructions manually provided.
				outputs->act_TRADE = 0;
				
			} 

			break;

		
	}

	//select transition to advance state
	switch(me->_policy_BlockIlliquidTrade_state) {
		case POLICY_STATE_Liquidity_BlockIlliquidTrade_s0:
			
			if(inputs->is_illiquid && !(outputs->act_TRADE)) {
				//transition s0 -> s0 on ( is_illiquid and !act_TRADE )
				me->_policy_BlockIlliquidTrade_state = POLICY_STATE_Liquidity_BlockIlliquidTrade_s0;
				//set expressions
				
				break;
			} 
			if( !(inputs->is_illiquid)) {
				//transition s0 -> s0 on ( !is_illiquid )
				me->_policy_BlockIlliquidTrade_state = POLICY_STATE_Liquidity_BlockIlliquidTrade_s0;
				//set expressions
				
				break;
			} 
			if(inputs->is_illiquid && outputs->act_TRADE) {
				//transition s0 -> violation on ( is_illiquid and act_TRADE )
				me->_policy_BlockIlliquidTrade_state = POLICY_STATE_Liquidity_BlockIlliquidTrade_violation;
				//set expressions
				
				break;
			} 
			
			//ensure a transition was taken in this state
			assert(false && "Liquidity_BlockIlliquidTrade_s0 must take a transition"); //if we are still here, then no transition was taken and we are no longer satisfying liveness

			break;

		
	}

	//ensure we did not violate (i.e. we did not enter violation state)
	assert(me->_policy_BlockIlliquidTrade_state != POLICY_STATE_Liquidity_BlockIlliquidTrade_violation);
}

//OUTPUT POLICY BlockIlliquidTrade END



//This function is provided in "F_Liquidity.c"
//It will check the state of the enforcer monitor code
//It returns one of the following:
//0: currently true (safe)
//1: always true (safe)
//-1: currently false (unsafe)
//-2: always false (unsafe)
//It will need to do some reachability analysis to achieve this

