
//This file should be called cbmc_main_KillSwitch.c
//This is autogenerated code. Edit by hand at your peril!

//It can be used with the cbmc model checker
//Call it using the following command: 
//$ cbmc cbmc_main_KillSwitch.c F_KillSwitch.c


#include "F_KillSwitch.h"
#include <stdio.h>
#include <stdint.h>

int main() {


	//I/O and state for KillSwitch
	enforcervars_KillSwitch_t enf_KillSwitch;
    inputs_KillSwitch_t inputs_KillSwitch;
    outputs_KillSwitch_t outputs_KillSwitch;

	//set values to known state
    KillSwitch_init_all_vars(&enf_KillSwitch, &inputs_KillSwitch, &outputs_KillSwitch);

	//introduce nondeterminism
    //a nondet_xxxxx function name tells cbmc that it could be anything, but must be unique
    //randomise inputs
	inputs_KillSwitch.dd_exceeded = nondet_KillSwitch_input_0();
	

	//randomise enforcer state, i.e. clock values and position (excepting violation state)
	
	enf_KillSwitch._policy_LatchingKillSwitch_state = nondet_KillSwitch_enf_LatchingKillSwitch_state() % 1;
	

    //run the enforcer (i.e. tell CBMC to check this out)
	KillSwitch_run_via_enforcer(&enf_KillSwitch, &inputs_KillSwitch, &outputs_KillSwitch);

}


void KillSwitch_run(inputs_KillSwitch_t *inputs, outputs_KillSwitch_t *outputs) {
    //randomise controller

    outputs->act_TRADE = nondet_KillSwitch_output_0();
	 
}

