
//This file should be called F_KillSwitch.c
//This is autogenerated code. Edit by hand at your peril!
#include "F_KillSwitch.h"

void KillSwitch_init_all_vars(enforcervars_KillSwitch_t* me, inputs_KillSwitch_t* inputs, outputs_KillSwitch_t* outputs) {
	//set any input vars with default values
	
	//set any output vars with default values
	

	
	me->_policy_LatchingKillSwitch_state = POLICY_STATE_KillSwitch_LatchingKillSwitch_s0;
	//input policy internal vars
	
	
}

void KillSwitch_run_via_enforcer(enforcervars_KillSwitch_t* me, inputs_KillSwitch_t* inputs, outputs_KillSwitch_t* outputs) {
	//run the policies in reverse order for the inputs (last policies have highest priority)
	
	 KillSwitch_run_input_enforcer_LatchingKillSwitch(me, inputs);
	

	KillSwitch_run(inputs, outputs);

	//run policies in specified order for outputs
	KillSwitch_run_output_enforcer_LatchingKillSwitch(me, inputs,outputs);
	
}


//input policies

//INPUT POLICY LatchingKillSwitch BEGIN
//This will run the input enforcer for KillSwitch's policy LatchingKillSwitch
void KillSwitch_run_input_enforcer_LatchingKillSwitch(enforcervars_KillSwitch_t* me, inputs_KillSwitch_t* inputs) {
	switch(me->_policy_LatchingKillSwitch_state) {
		case POLICY_STATE_KillSwitch_LatchingKillSwitch_s0:
			
			if(inputs->dd_exceeded) {
				//transition s0 -> violation on dd_exceeded
				//select a transition to solve the problem
				
				//Recovery instructions manually provided.
				
			} 
			if(inputs->dd_exceeded) {
				//transition s0 -> violation on dd_exceeded
				//select a transition to solve the problem
				
				//Selected non-violation transition "s0 -> s0 on not (dd_exceeded)" and action is required
				inputs->dd_exceeded = 0;
				
			} 
			
			break;

		
	}
}

//INPUT POLICY LatchingKillSwitch END



//output policies

//OUTPUT POLICY LatchingKillSwitch BEGIN
//This will run the input enforcer for KillSwitch's policy LatchingKillSwitch
void KillSwitch_run_output_enforcer_LatchingKillSwitch(enforcervars_KillSwitch_t* me, inputs_KillSwitch_t* inputs, outputs_KillSwitch_t* outputs) {
	//advance timers
	
	
	//run enforcer
	switch(me->_policy_LatchingKillSwitch_state) {
		case POLICY_STATE_KillSwitch_LatchingKillSwitch_s0:
			
			if(inputs->dd_exceeded && outputs->act_TRADE) {
				//transition s0 -> violation on ( dd_exceeded and act_TRADE )
				//select a transition to solve the problem
				
				//Recovery instructions manually provided.
				outputs->act_TRADE = 0;
				
			} 
			if(inputs->dd_exceeded && !(outputs->act_TRADE)) {
				//transition s0 -> violation on ( dd_exceeded and !act_TRADE )
				//select a transition to solve the problem
				
				//Selected non-violation transition "s0 -> s0 on ( !dd_exceeded )" and action was not required
				
			} 

			break;

		
	}

	//select transition to advance state
	switch(me->_policy_LatchingKillSwitch_state) {
		case POLICY_STATE_KillSwitch_LatchingKillSwitch_s0:
			
			if( !(inputs->dd_exceeded)) {
				//transition s0 -> s0 on ( !dd_exceeded )
				me->_policy_LatchingKillSwitch_state = POLICY_STATE_KillSwitch_LatchingKillSwitch_s0;
				//set expressions
				
				break;
			} 
			if(inputs->dd_exceeded && outputs->act_TRADE) {
				//transition s0 -> violation on ( dd_exceeded and act_TRADE )
				me->_policy_LatchingKillSwitch_state = POLICY_STATE_KillSwitch_LatchingKillSwitch_violation;
				//set expressions
				
				break;
			} 
			if(inputs->dd_exceeded && !(outputs->act_TRADE)) {
				//transition s0 -> violation on ( dd_exceeded and !act_TRADE )
				me->_policy_LatchingKillSwitch_state = POLICY_STATE_KillSwitch_LatchingKillSwitch_violation;
				//set expressions
				
				break;
			} 
			
			//ensure a transition was taken in this state
			assert(false && "KillSwitch_LatchingKillSwitch_s0 must take a transition"); //if we are still here, then no transition was taken and we are no longer satisfying liveness

			break;

		
	}

	//ensure we did not violate (i.e. we did not enter violation state)
	assert(me->_policy_LatchingKillSwitch_state != POLICY_STATE_KillSwitch_LatchingKillSwitch_violation);
}

//OUTPUT POLICY LatchingKillSwitch END



//This function is provided in "F_KillSwitch.c"
//It will check the state of the enforcer monitor code
//It returns one of the following:
//0: currently true (safe)
//1: always true (safe)
//-1: currently false (unsafe)
//-2: always false (unsafe)
//It will need to do some reachability analysis to achieve this

