
//This file should be called F_KillSwitch.h
//This is autogenerated code. Edit by hand at your peril!

#include <stdint.h>
#include <stdbool.h>
#include <assert.h>

//the dtimer_t type
typedef uint64_t dtimer_t;

//For each policy, we need an enum type for the state machine

enum KillSwitch_policy_LatchingKillSwitch_states { 
	POLICY_STATE_KillSwitch_LatchingKillSwitch_s0,
	POLICY_STATE_KillSwitch_LatchingKillSwitch_violation 
};


//Inputs to the function KillSwitch
typedef struct {
	bool dd_exceeded;
	
} inputs_KillSwitch_t;

//Outputs from the function KillSwitch
typedef struct {
	bool act_TRADE;
	
} outputs_KillSwitch_t;

//enforcer state and vars:
typedef struct {
	enum KillSwitch_policy_LatchingKillSwitch_states _policy_LatchingKillSwitch_state;
	//internal vars
	
	
	
} enforcervars_KillSwitch_t;



//This function is provided in "F_KillSwitch.c"
//It sets up the variable structures to their initial values
void KillSwitch_init_all_vars(enforcervars_KillSwitch_t* me, inputs_KillSwitch_t* inputs, outputs_KillSwitch_t* outputs);

//This function is provided in "F_KillSwitch.c"
//It will run the synthesised enforcer and call the controller function
void KillSwitch_run_via_enforcer(enforcervars_KillSwitch_t* me, inputs_KillSwitch_t* inputs, outputs_KillSwitch_t* outputs);

//This function is provided from the user
//It is the controller function
extern void KillSwitch_run(inputs_KillSwitch_t* inputs, outputs_KillSwitch_t* outputs);

//enforcer functions


//This function is provided in "F_KillSwitch.c"
//It will run the input enforcer for KillSwitch's policy LatchingKillSwitch
void KillSwitch_run_input_enforcer_LatchingKillSwitch(enforcervars_KillSwitch_t* me, inputs_KillSwitch_t* inputs);

//This function is provided in "F_KillSwitch.c"
//It will run the input enforcer for KillSwitch's policy LatchingKillSwitch
void KillSwitch_run_output_enforcer_LatchingKillSwitch(enforcervars_KillSwitch_t* me, inputs_KillSwitch_t* inputs, outputs_KillSwitch_t* outputs);

//This function is provided in "F_KillSwitch.c"
//It will check the state of the enforcer monitor code
//It returns one of the following:
//0: currently true (safe)
//1: always true (safe)
//-1: currently false (unsafe)
//-2: always false (unsafe)
//It will need to do some reachability analysis to achieve this
int KillSwitch_check_rv_status_LatchingKillSwitch(enforcervars_KillSwitch_t* me);


