
//This file should be called cbmc_main_WashTrading.c
//This is autogenerated code. Edit by hand at your peril!

//It can be used with the cbmc model checker
//Call it using the following command: 
//$ cbmc cbmc_main_WashTrading.c F_WashTrading.c


#include "F_WashTrading.h"
#include <stdio.h>
#include <stdint.h>

int main() {


	//I/O and state for WashTrading
	enforcervars_WashTrading_t enf_WashTrading;
    inputs_WashTrading_t inputs_WashTrading;
    outputs_WashTrading_t outputs_WashTrading;

	//set values to known state
    WashTrading_init_all_vars(&enf_WashTrading, &inputs_WashTrading, &outputs_WashTrading);

	//introduce nondeterminism
    //a nondet_xxxxx function name tells cbmc that it could be anything, but must be unique
    //randomise inputs
	

	//randomise enforcer state, i.e. clock values and position (excepting violation state)
	enf_WashTrading.last_bid = nondet_WashTrading_enf_NoWash_0();
	enf_WashTrading.last_ask = nondet_WashTrading_enf_NoWash_1();
	
	enf_WashTrading._policy_NoWash_state = nondet_WashTrading_enf_NoWash_state() % 3;
	

    //run the enforcer (i.e. tell CBMC to check this out)
	WashTrading_run_via_enforcer(&enf_WashTrading, &inputs_WashTrading, &outputs_WashTrading);

}


void WashTrading_run(inputs_WashTrading_t *inputs, outputs_WashTrading_t *outputs) {
    //randomise controller

    outputs->act_BUY = nondet_WashTrading_output_0();
	outputs->act_SELL = nondet_WashTrading_output_1();
	outputs->price = nondet_WashTrading_output_2();
	 
}

