
//This file should be called F_WashTrading.h
//This is autogenerated code. Edit by hand at your peril!

#include <stdint.h>
#include <stdbool.h>
#include <assert.h>

//the dtimer_t type
typedef uint64_t dtimer_t;

//For each policy, we need an enum type for the state machine

enum WashTrading_policy_NoWash_states { 
	POLICY_STATE_WashTrading_NoWash_s0, 
	POLICY_STATE_WashTrading_NoWash_s1, 
	POLICY_STATE_WashTrading_NoWash_s2,
	POLICY_STATE_WashTrading_NoWash_violation 
};


//Inputs to the function WashTrading
typedef struct {
	
} inputs_WashTrading_t;

//Outputs from the function WashTrading
typedef struct {
	bool act_BUY;
	bool act_SELL;
	int32_t price;
	
} outputs_WashTrading_t;

//enforcer state and vars:
typedef struct {
	enum WashTrading_policy_NoWash_states _policy_NoWash_state;
	//internal vars
	int32_t last_bid;
	int32_t last_ask;
	
	
	
} enforcervars_WashTrading_t;





//This function is provided in "F_WashTrading.c"
//It sets up the variable structures to their initial values
void WashTrading_init_all_vars(enforcervars_WashTrading_t* me, inputs_WashTrading_t* inputs, outputs_WashTrading_t* outputs);

//This function is provided in "F_WashTrading.c"
//It will run the synthesised enforcer and call the controller function
void WashTrading_run_via_enforcer(enforcervars_WashTrading_t* me, inputs_WashTrading_t* inputs, outputs_WashTrading_t* outputs);

//This function is provided from the user
//It is the controller function
extern void WashTrading_run(inputs_WashTrading_t* inputs, outputs_WashTrading_t* outputs);

//enforcer functions


//This function is provided in "F_WashTrading.c"
//It will run the input enforcer for WashTrading's policy NoWash
void WashTrading_run_input_enforcer_NoWash(enforcervars_WashTrading_t* me, inputs_WashTrading_t* inputs);

//This function is provided in "F_WashTrading.c"
//It will run the input enforcer for WashTrading's policy NoWash
void WashTrading_run_output_enforcer_NoWash(enforcervars_WashTrading_t* me, inputs_WashTrading_t* inputs, outputs_WashTrading_t* outputs);

//This function is provided in "F_WashTrading.c"
//It will check the state of the enforcer monitor code
//It returns one of the following:
//0: currently true (safe)
//1: always true (safe)
//-1: currently false (unsafe)
//-2: always false (unsafe)
//It will need to do some reachability analysis to achieve this
int WashTrading_check_rv_status_NoWash(enforcervars_WashTrading_t* me);


