
//This file should be called F_WashTrading.c
//This is autogenerated code. Edit by hand at your peril!
#include "F_WashTrading.h"

void WashTrading_init_all_vars(enforcervars_WashTrading_t* me, inputs_WashTrading_t* inputs, outputs_WashTrading_t* outputs) {
	//set any input vars with default values
	
	//set any output vars with default values
	

	
	me->_policy_NoWash_state = POLICY_STATE_WashTrading_NoWash_s0;
	//input policy internal vars
	
	me->last_bid = 0;
	
	me->last_ask = 4000000000;
	
	
}

void WashTrading_run_via_enforcer(enforcervars_WashTrading_t* me, inputs_WashTrading_t* inputs, outputs_WashTrading_t* outputs) {
	//run the policies in reverse order for the inputs (last policies have highest priority)
	
	 WashTrading_run_input_enforcer_NoWash(me, inputs);
	

	WashTrading_run(inputs, outputs);

	//run policies in specified order for outputs
	WashTrading_run_output_enforcer_NoWash(me, inputs,outputs);
	
}


//input policies

//INPUT POLICY NoWash BEGIN
//This will run the input enforcer for WashTrading's policy NoWash
void WashTrading_run_input_enforcer_NoWash(enforcervars_WashTrading_t* me, inputs_WashTrading_t* inputs) {
	switch(me->_policy_NoWash_state) {
		case POLICY_STATE_WashTrading_NoWash_s0:
			
			
			break;

		case POLICY_STATE_WashTrading_NoWash_s1:
			
			
			break;

		case POLICY_STATE_WashTrading_NoWash_s2:
			
			
			break;

		
	}
}

//INPUT POLICY NoWash END



//output policies

//OUTPUT POLICY NoWash BEGIN
//This will run the input enforcer for WashTrading's policy NoWash
void WashTrading_run_output_enforcer_NoWash(enforcervars_WashTrading_t* me, inputs_WashTrading_t* inputs, outputs_WashTrading_t* outputs) {
	//advance timers
	
	
	//run enforcer
	switch(me->_policy_NoWash_state) {
		case POLICY_STATE_WashTrading_NoWash_s0:
			

			break;

		case POLICY_STATE_WashTrading_NoWash_s1:
			
			if(outputs->act_SELL && outputs->price <= me->last_bid) {
				//transition s1 -> violation on ( act_SELL and price <= last_bid )
				//select a transition to solve the problem
				
				//Recovery instructions manually provided.
				outputs->act_SELL = 0;
				
			} 

			break;

		case POLICY_STATE_WashTrading_NoWash_s2:
			
			if(outputs->act_BUY && outputs->price >= me->last_ask) {
				//transition s2 -> violation on ( act_BUY and price >= last_ask )
				//select a transition to solve the problem
				
				//Recovery instructions manually provided.
				outputs->act_BUY = 0;
				
			} 

			break;

		
	}

	//select transition to advance state
	switch(me->_policy_NoWash_state) {
		case POLICY_STATE_WashTrading_NoWash_s0:
			
			if(outputs->act_BUY) {
				//transition s0 -> s1 on act_BUY
				me->_policy_NoWash_state = POLICY_STATE_WashTrading_NoWash_s1;
				//set expressions
				
				me->last_bid = price;
				break;
			} 
			if(outputs->act_SELL) {
				//transition s0 -> s2 on act_SELL
				me->_policy_NoWash_state = POLICY_STATE_WashTrading_NoWash_s2;
				//set expressions
				
				me->last_ask = price;
				break;
			} 
			if( !(outputs->act_BUY) && !(outputs->act_SELL)) {
				//transition s0 -> s0 on ( !act_BUY and !act_SELL )
				me->_policy_NoWash_state = POLICY_STATE_WashTrading_NoWash_s0;
				//set expressions
				
				break;
			} 
			
			//ensure a transition was taken in this state
			assert(false && "WashTrading_NoWash_s0 must take a transition"); //if we are still here, then no transition was taken and we are no longer satisfying liveness

			break;

		case POLICY_STATE_WashTrading_NoWash_s1:
			
			if(outputs->act_BUY) {
				//transition s1 -> s1 on act_BUY
				me->_policy_NoWash_state = POLICY_STATE_WashTrading_NoWash_s1;
				//set expressions
				
				me->last_bid = price;
				break;
			} 
			if(outputs->act_SELL && outputs->price > me->last_bid) {
				//transition s1 -> s2 on ( act_SELL and price > last_bid )
				me->_policy_NoWash_state = POLICY_STATE_WashTrading_NoWash_s2;
				//set expressions
				
				me->last_ask = price;
				break;
			} 
			if( !(outputs->act_BUY) && !(outputs->act_SELL)) {
				//transition s1 -> s1 on ( !act_BUY and !act_SELL )
				me->_policy_NoWash_state = POLICY_STATE_WashTrading_NoWash_s1;
				//set expressions
				
				break;
			} 
			if(outputs->act_SELL && outputs->price <= me->last_bid) {
				//transition s1 -> violation on ( act_SELL and price <= last_bid )
				me->_policy_NoWash_state = POLICY_STATE_WashTrading_NoWash_violation;
				//set expressions
				
				break;
			} 
			
			//ensure a transition was taken in this state
			assert(false && "WashTrading_NoWash_s1 must take a transition"); //if we are still here, then no transition was taken and we are no longer satisfying liveness

			break;

		case POLICY_STATE_WashTrading_NoWash_s2:
			
			if(outputs->act_SELL) {
				//transition s2 -> s2 on act_SELL
				me->_policy_NoWash_state = POLICY_STATE_WashTrading_NoWash_s2;
				//set expressions
				
				me->last_ask = price;
				break;
			} 
			if(outputs->act_BUY && outputs->price < me->last_ask) {
				//transition s2 -> s1 on ( act_BUY and price < last_ask )
				me->_policy_NoWash_state = POLICY_STATE_WashTrading_NoWash_s1;
				//set expressions
				
				me->last_bid = price;
				break;
			} 
			if( !(outputs->act_BUY) && !(outputs->act_SELL)) {
				//transition s2 -> s2 on ( !act_BUY and !act_SELL )
				me->_policy_NoWash_state = POLICY_STATE_WashTrading_NoWash_s2;
				//set expressions
				
				break;
			} 
			if(outputs->act_BUY && outputs->price >= me->last_ask) {
				//transition s2 -> violation on ( act_BUY and price >= last_ask )
				me->_policy_NoWash_state = POLICY_STATE_WashTrading_NoWash_violation;
				//set expressions
				
				break;
			} 
			
			//ensure a transition was taken in this state
			assert(false && "WashTrading_NoWash_s2 must take a transition"); //if we are still here, then no transition was taken and we are no longer satisfying liveness

			break;

		
	}

	//ensure we did not violate (i.e. we did not enter violation state)
	assert(me->_policy_NoWash_state != POLICY_STATE_WashTrading_NoWash_violation);
}

//OUTPUT POLICY NoWash END



//This function is provided in "F_WashTrading.c"
//It will check the state of the enforcer monitor code
//It returns one of the following:
//0: currently true (safe)
//1: always true (safe)
//-1: currently false (unsafe)
//-2: always false (unsafe)
//It will need to do some reachability analysis to achieve this

