
//This file should be called cbmc_main_PositionConcentration.c
//This is autogenerated code. Edit by hand at your peril!

//It can be used with the cbmc model checker
//Call it using the following command: 
//$ cbmc cbmc_main_PositionConcentration.c F_PositionConcentration.c


#include "F_PositionConcentration.h"
#include <stdio.h>
#include <stdint.h>

int main() {


	//I/O and state for PositionConcentration
	enforcervars_PositionConcentration_t enf_PositionConcentration;
    inputs_PositionConcentration_t inputs_PositionConcentration;
    outputs_PositionConcentration_t outputs_PositionConcentration;

	//set values to known state
    PositionConcentration_init_all_vars(&enf_PositionConcentration, &inputs_PositionConcentration, &outputs_PositionConcentration);

	//introduce nondeterminism
    //a nondet_xxxxx function name tells cbmc that it could be anything, but must be unique
    //randomise inputs
	inputs_PositionConcentration.will_exceed_limit = nondet_PositionConcentration_input_0();
	

	//randomise enforcer state, i.e. clock values and position (excepting violation state)
	
	enf_PositionConcentration._policy_BlockConcentratedBuy_state = nondet_PositionConcentration_enf_BlockConcentratedBuy_state() % 1;
	

    //run the enforcer (i.e. tell CBMC to check this out)
	PositionConcentration_run_via_enforcer(&enf_PositionConcentration, &inputs_PositionConcentration, &outputs_PositionConcentration);

}


void PositionConcentration_run(inputs_PositionConcentration_t *inputs, outputs_PositionConcentration_t *outputs) {
    //randomise controller

    outputs->act_BUY = nondet_PositionConcentration_output_0();
	 
}

