
//This file should be called F_PositionConcentration.h
//This is autogenerated code. Edit by hand at your peril!

#include <stdint.h>
#include <stdbool.h>
#include <assert.h>

//the dtimer_t type
typedef uint64_t dtimer_t;

//For each policy, we need an enum type for the state machine

enum PositionConcentration_policy_BlockConcentratedBuy_states { 
	POLICY_STATE_PositionConcentration_BlockConcentratedBuy_s0,
	POLICY_STATE_PositionConcentration_BlockConcentratedBuy_violation 
};


//Inputs to the function PositionConcentration
typedef struct {
	bool will_exceed_limit;
	
} inputs_PositionConcentration_t;

//Outputs from the function PositionConcentration
typedef struct {
	bool act_BUY;
	
} outputs_PositionConcentration_t;

//enforcer state and vars:
typedef struct {
	enum PositionConcentration_policy_BlockConcentratedBuy_states _policy_BlockConcentratedBuy_state;
	//internal vars
	
	
	
} enforcervars_PositionConcentration_t;



//This function is provided in "F_PositionConcentration.c"
//It sets up the variable structures to their initial values
void PositionConcentration_init_all_vars(enforcervars_PositionConcentration_t* me, inputs_PositionConcentration_t* inputs, outputs_PositionConcentration_t* outputs);

//This function is provided in "F_PositionConcentration.c"
//It will run the synthesised enforcer and call the controller function
void PositionConcentration_run_via_enforcer(enforcervars_PositionConcentration_t* me, inputs_PositionConcentration_t* inputs, outputs_PositionConcentration_t* outputs);

//This function is provided from the user
//It is the controller function
extern void PositionConcentration_run(inputs_PositionConcentration_t* inputs, outputs_PositionConcentration_t* outputs);

//enforcer functions


//This function is provided in "F_PositionConcentration.c"
//It will run the input enforcer for PositionConcentration's policy BlockConcentratedBuy
void PositionConcentration_run_input_enforcer_BlockConcentratedBuy(enforcervars_PositionConcentration_t* me, inputs_PositionConcentration_t* inputs);

//This function is provided in "F_PositionConcentration.c"
//It will run the input enforcer for PositionConcentration's policy BlockConcentratedBuy
void PositionConcentration_run_output_enforcer_BlockConcentratedBuy(enforcervars_PositionConcentration_t* me, inputs_PositionConcentration_t* inputs, outputs_PositionConcentration_t* outputs);

//This function is provided in "F_PositionConcentration.c"
//It will check the state of the enforcer monitor code
//It returns one of the following:
//0: currently true (safe)
//1: always true (safe)
//-1: currently false (unsafe)
//-2: always false (unsafe)
//It will need to do some reachability analysis to achieve this
int PositionConcentration_check_rv_status_BlockConcentratedBuy(enforcervars_PositionConcentration_t* me);


