
//This file should be called F_PositionConcentration.c
//This is autogenerated code. Edit by hand at your peril!
#include "F_PositionConcentration.h"

void PositionConcentration_init_all_vars(enforcervars_PositionConcentration_t* me, inputs_PositionConcentration_t* inputs, outputs_PositionConcentration_t* outputs) {
	//set any input vars with default values
	
	//set any output vars with default values
	

	
	me->_policy_BlockConcentratedBuy_state = POLICY_STATE_PositionConcentration_BlockConcentratedBuy_s0;
	//input policy internal vars
	
	
}

void PositionConcentration_run_via_enforcer(enforcervars_PositionConcentration_t* me, inputs_PositionConcentration_t* inputs, outputs_PositionConcentration_t* outputs) {
	//run the policies in reverse order for the inputs (last policies have highest priority)
	
	 PositionConcentration_run_input_enforcer_BlockConcentratedBuy(me, inputs);
	

	PositionConcentration_run(inputs, outputs);

	//run policies in specified order for outputs
	PositionConcentration_run_output_enforcer_BlockConcentratedBuy(me, inputs,outputs);
	
}


//input policies

//INPUT POLICY BlockConcentratedBuy BEGIN
//This will run the input enforcer for PositionConcentration's policy BlockConcentratedBuy
void PositionConcentration_run_input_enforcer_BlockConcentratedBuy(enforcervars_PositionConcentration_t* me, inputs_PositionConcentration_t* inputs) {
	switch(me->_policy_BlockConcentratedBuy_state) {
		case POLICY_STATE_PositionConcentration_BlockConcentratedBuy_s0:
			
			if(inputs->will_exceed_limit) {
				//transition s0 -> violation on will_exceed_limit
				//select a transition to solve the problem
				
				//Selected non-violation transition "s0 -> s0 on will_exceed_limit" which has an equivalent guard, so no action is required
				
			} 
			
			break;

		
	}
}

//INPUT POLICY BlockConcentratedBuy END



//output policies

//OUTPUT POLICY BlockConcentratedBuy BEGIN
//This will run the input enforcer for PositionConcentration's policy BlockConcentratedBuy
void PositionConcentration_run_output_enforcer_BlockConcentratedBuy(enforcervars_PositionConcentration_t* me, inputs_PositionConcentration_t* inputs, outputs_PositionConcentration_t* outputs) {
	//advance timers
	
	
	//run enforcer
	switch(me->_policy_BlockConcentratedBuy_state) {
		case POLICY_STATE_PositionConcentration_BlockConcentratedBuy_s0:
			
			if(inputs->will_exceed_limit && outputs->act_BUY) {
				//transition s0 -> violation on ( will_exceed_limit and act_BUY )
				//select a transition to solve the problem
				
				//Recovery instructions manually provided.
				outputs->act_BUY = 0;
				
			} 

			break;

		
	}

	//select transition to advance state
	switch(me->_policy_BlockConcentratedBuy_state) {
		case POLICY_STATE_PositionConcentration_BlockConcentratedBuy_s0:
			
			if(inputs->will_exceed_limit && !(outputs->act_BUY)) {
				//transition s0 -> s0 on ( will_exceed_limit and !act_BUY )
				me->_policy_BlockConcentratedBuy_state = POLICY_STATE_PositionConcentration_BlockConcentratedBuy_s0;
				//set expressions
				
				break;
			} 
			if( !(inputs->will_exceed_limit)) {
				//transition s0 -> s0 on ( !will_exceed_limit )
				me->_policy_BlockConcentratedBuy_state = POLICY_STATE_PositionConcentration_BlockConcentratedBuy_s0;
				//set expressions
				
				break;
			} 
			if(inputs->will_exceed_limit && outputs->act_BUY) {
				//transition s0 -> violation on ( will_exceed_limit and act_BUY )
				me->_policy_BlockConcentratedBuy_state = POLICY_STATE_PositionConcentration_BlockConcentratedBuy_violation;
				//set expressions
				
				break;
			} 
			
			//ensure a transition was taken in this state
			assert(false && "PositionConcentration_BlockConcentratedBuy_s0 must take a transition"); //if we are still here, then no transition was taken and we are no longer satisfying liveness

			break;

		
	}

	//ensure we did not violate (i.e. we did not enter violation state)
	assert(me->_policy_BlockConcentratedBuy_state != POLICY_STATE_PositionConcentration_BlockConcentratedBuy_violation);
}

//OUTPUT POLICY BlockConcentratedBuy END



//This function is provided in "F_PositionConcentration.c"
//It will check the state of the enforcer monitor code
//It returns one of the following:
//0: currently true (safe)
//1: always true (safe)
//-1: currently false (unsafe)
//-2: always false (unsafe)
//It will need to do some reachability analysis to achieve this

